In [8]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
df=pd.read_csv('ANFR_Herault_Mesures_originales_pour_jpynb_V2.csv', delimiter=';')
df.head()

,Numero de mesure,Longitude,Latitude,Position,Insee,Adresse,Complement,Code postal,Commune,Date de mesure,Mesure realisee,Rapport,Conformite de la mesure,Niveau global,Type d'environnement,Laboratoire
0,175,3.91611,43.58528,"03e 54' 58.00'' Est, 43e 35' 07.00'' Nord",34129,Mas de Gau,NaN,34970,LATTES,06/12/2001,En exterieur,FicheMesure175.pdf,Oui,0.00,Divers,SATELIT
1,180,4.04194,43.64694,"04e 02' 31.00'' Est, 43e 38' 49.00'' Nord",34176,5539 Rue Lou Claou de la Oulivettas,NaN,34130,MUDAISON,06/12/2001,En exterieur,FicheMesure180.pdf,Oui,0.00,Divers,SATELIT
2,543,3.03167,43.36028,"03e 01' 54.00'' Est, 43e 21' 37.00'' Nord",34225,Chemin de Montfaucon,residence de Mme SOUTADE,34620,PUISSERGUIER,23/05/2002,En exterieur,FicheMesure543.pdf,Oui,0.54,Divers,APAVE
3,545,3.03278,43.36167,"03e 01' 58.00'' Est, 43e 21' 42.00'' Nord",34225,Chemin de Quarante,residence de M. GONZALEZ,34620,PUISSERGUIER,23/05/2002,En exterieur,FicheMesure545.pdf,Oui,0.20,Divers,APAVE
4,850,3.56444,43.64583,"03e 33' 52.00'' Est, 43e 38' 45.00'' Nord",34114,480 Chemin de Pioch Courbi,Chez Mme et M. GALOIS,34150,GIGNAC,10/10/2002,En exterieur,FicheMesure850.pdf,Oui,0.53,Rue / Route / Parking,APAVE

In [9]:
df.rename(columns={'Niveau global': 'Niveau_global'}, inplace=True)

In [10]:
df=df.assign(target=1)

In [15]:
# A list with missing entries
def add_line ():
    for i in range(0,10):
        Niveau_glb = random.uniform(1,6)
        Numéro_de_mesure =random.randint(2000,4000)
        row_contents = [Numéro_de_mesure, 3.91611,43.64694, 'Est, 43e 35 07.00 Nord',34176,
       'Chemin de Montfaucon','residence de Mme SOUTADE',34130,'LATTES','06/12/2001','En exterieure', 
                    'FicheMesure175.pdf', 'Oui', Niveau_glb, 'Divers', 'SATELIT', 1]
        # Appending a row to csv with missing entries
        append_list_as_row('ANFR_Herault_Mesures_originales_pour_jpynb_V2.csv', row_contents)

In [16]:
add_line()

NameError: name 'append_list_as_row' is not defined